@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjhlYmRmOWM5OThjMDAyYTQyZTA3NzAiLCJpYXQiOjE2MDMxOTAyNzcsImV4cCI6MTYwMzI1NTA3N30.-dDibI9zzNrexbKLH0tCxxsI-ph81E-sMUM3_rDmwaY

### Get the Single image
GET {{host}}/upload/788e99e0a2fe3212cab982fd1bc0bbe2

### post img
POST {{host}}/upload/
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="img"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary--
