@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjcwMGIzOWRmYjJhNTQxMjg1MDk2MmIiLCJpYXQiOjE2MDExNzg0NDEsImV4cCI6MTYwMTI0MzI0MX0.R5eaCy_Qhkc31QiDi-XJLDn2NWZZCh17ruNzw0rKjm0

### get onlyphotos 
GET {{host}}/post/onlyphotos/5f700b39dfb2a5412850962b/?skip=5
Authorization: {{token}}

### get my post 
GET {{host}}/post/mypost/?skip=5
Authorization: {{token}}

### get all post 
GET {{host}}/post/allpost/?skip=5
Authorization: {{token}}

### get sub post 
GET {{host}}/post/getsubpost/?skip=5
Authorization: {{token}}

### create post
POST {{host}}/post/createpost
Content-Type: application/json
Authorization: {{token}}

{
    "title": "title3",
    "body" : "body3",
    "picUrl" : "pic3"
}

### like post
PUT {{host}}/post/like
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f5dbbd8c364ef27082d548f"
}

### unlike post
PUT {{host}}/post/unlike
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f5dbbd8c364ef27082d548f"
}


### hearted post
PUT {{host}}/post/hearted
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f5dbbd8c364ef27082d548f"
}

### unhearted post
PUT {{host}}/post/unhearted
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f5dbbd8c364ef27082d548f"
}

### comment post
PUT {{host}}/post/comment
Content-Type: application/json
Authorization: {{token}}

{
    "text": "super2222",
    "postId" : "5f5f15d796a0272298366839"
}

### delete
DELETE  {{host}}/post/5f5dbfad599d6d34246e4a71
Content-Type: application/json
Authorization: {{token}}
