@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjhhN2Y3MjRiMzNhMjA2MDAzMzNmNWUiLCJpYXQiOjE2MDI5OTc5MzMsImV4cCI6MTYwMzA2MjczM30.bnlR84viIgCxF2FO1sekz6WusmDiS9bjtmaT4ANddIg

### get onlyphotos 
GET {{host}}/post/onlyphotos/5f8a7f724b33a20600333f5e/?skip=6
Authorization: {{token}}

### get my post 
GET {{host}}/post/mypost/?skip=5
Authorization: {{token}}

### get all post 
GET {{host}}/post/allpost/?skip=5
Authorization: {{token}}

### get sub post 
GET {{host}}/post/getsubpost/?skip=5
Authorization: {{token}}

### create post
POST {{host}}/post/createpost
Content-Type: application/json
Authorization: {{token}}

{
    "title" : "title3",
    "body" : "body3",
    "picUrl" : "5ffea9e3f5a15f09fcd219fe8484b136"
}

### like post
PUT {{host}}/post/like
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f8a853c066cb3316caf1c96"
}

### unlike post
PUT {{host}}/post/unlike
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f8a853c066cb3316caf1c96"
}

### hearted post
PUT {{host}}/post/hearted
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f8a853c066cb3316caf1c96"
}

### unhearted post
PUT {{host}}/post/unhearted
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f8a853c066cb3316caf1c96"
}

### comment post
PUT {{host}}/post/comment
Content-Type: application/json
Authorization: {{token}}

{
    "text": "actual",
    "postId" : "5f8a853c066cb3316caf1c96"
}

### delete comment
DELETE {{host}}/post/comment
Content-Type: application/json
Authorization: {{token}}

{
    "postId" : "5f8a853c066cb3316caf1c96",
    "commentId" : "5f8ad3326230f64ba885fe8f"
}

### delete
DELETE  {{host}}/post/5f8ad2b6f8babb36a4f14d99
Content-Type: application/json
Authorization: {{token}}

### delete all posts of user
DELETE  {{host}}/post/
Content-Type: application/json
Authorization: {{token}}
