@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjhhN2Y3MjRiMzNhMjA2MDAzMzNmNWUiLCJpYXQiOjE2MDI5OTc5MzMsImV4cCI6MTYwMzA2MjczM30.bnlR84viIgCxF2FO1sekz6WusmDiS9bjtmaT4ANddIg

### get me 
GET {{host}}/user/me
Authorization: {{token}}

### get user by id
GET {{host}}/user/5f684c9b44974b3a587907ca
Authorization: {{token}}

### register
POST {{host}}/user/register
Content-Type: application/json

{
    "fullName" : "newname",
    "userName": "kiuj",
    "email" : "nnnaf@nnnn.com",
    "password" : "aA1!aaaa"
}

### login
POST {{host}}/user/login
Content-Type: application/json

{
    "email" : "mm@mmm.mmm",
    "password" : "aA1!aa"
}

### updatePass
PUT {{host}}/user
Content-Type: application/json
Authorization: {{token}}

{
    "email" : "kk@bb.bb",
    "oldPass" : "aA1!aaaa",
    "newPass" : "Aa1!abba"
}

### follow
PUT {{host}}/user/follow
Content-Type: application/json
Authorization: {{token}}

{
    "followId" : "5f5cae1de665bf35f420d4d2"
}

### unfollow
PUT {{host}}/user/unfollow
Content-Type: application/json
Authorization: {{token}}

{
    "unfollowId" : "5f5cae1de665bf35f420d4d2"
}

### save post
PUT {{host}}/user/savepost
Content-Type: application/json
Authorization: {{token}}

{
    "postId" : "5f8a83cc9f1252244818dc74"
}

### unsave post
PUT {{host}}/user/unsavepost
Content-Type: application/json
Authorization: {{token}}

{
    "postId" : "5f8a853b066cb3316caf1c95"
}

### reset password
POST {{host}}/user/reset-password
Content-Type: application/json
Authorization: {{token}}

{
    "email" : ""
}

### new password
POST {{host}}/user/new-password
Content-Type: application/json
Authorization: {{token}}

{
    "password" : "akssd@aa.bb",
    "token" : "afbacd0fc2b9a0842f3a49c3fcd0b026ec5267115eb04f87b14947faa1a49a31"
}

###search users
POST {{host}}/user/search-users
Authorization: {{token}}

{
    "query" : ""
}

### logout
POST {{host}}/user/logout
Content-Type: application/json
Authorization: {{token}}

### delete
DELETE  {{host}}/user
Content-Type: application/json
Authorization: {{token}}
