@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjkyMzlmZjdiYTBiYTMwMThhZDQ1OTMiLCJpYXQiOjE2MDM2MTc4MTgsImV4cCI6MTYwMzY4MjYxOH0.v2S5Q5XUWllMmtOGxHO_TIYPglAaaa0GRAkeWzzcvIQ

### get comments 
GET {{host}}/comment/5f95446a4b517f2810f2cc98/?skip=0
Content-Type: application/json
Authorization: {{token}}

### post comment
POST {{host}}/comment
Content-Type: application/json
Authorization: {{token}}

{
    "text": "raj 2",
    "postId" : "5f95446a4b517f2810f2cc98"
}

### put comment
PUT {{host}}/comment
Content-Type: application/json
Authorization: {{token}}

{
    "text": "actual iuhbjkkkkkhhffbbvb",
    "commentId" : "5f940eee0bf62a18740dd459"
}

### delete comment
DELETE {{host}}/comment
Content-Type: application/json
Authorization: {{token}}

{
    "postId" : "5f8ebec6c998c002a42e0782",
    "commentId" : "5f8f030eb4400c58b8bb2160"
}

