@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1Zjk3ZmM3MDQ2NTk4MDE1MGM4NjQzNzMiLCJpYXQiOjE2MDM5NjcyMDEsImV4cCI6MTYwNDAzMjAwMX0.uSRN57d3kAzsa0lV8lvVVImnNff5iuJ1bHexXUI59LU

### get comments 
GET {{host}}/comment/5f9a9969ff668f3b30f01894/?skip=0
Content-Type: application/json
Authorization: {{token}}

### post comment
POST {{host}}/comment
Content-Type: application/json
Authorization: {{token}}

{
    "text": "raj 2",
    "postId" : "5f9a9969ff668f3b30f01894"
}

### put comment
PUT {{host}}/comment
Content-Type: application/json
Authorization: {{token}}

{
    "text": "actual iuhbjkkkkkhhffbbvb",
    "commentId" : "5f940eee0bf62a18740dd459"
}

### delete comment
DELETE {{host}}/comment
Content-Type: application/json
Authorization: {{token}}

{
    "postId" : "5f8ebec6c998c002a42e0782",
    "commentId" : "5f8f030eb4400c58b8bb2160"
}

