@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1Zjk2NGIyOWI1NTVmOTJhOTAyMzI4MDIiLCJpYXQiOjE2MDM2ODU4NTEsImV4cCI6MTYwMzc1MDY1MX0.kbEuZ-vANVadEuE-LsaUqtH2wSMN59nDxhH1Fcq-ItU

DELETE {{host}}/delete
Authorization: {{token}}
