@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmEzZjdhOTgxMGJlNTI2OTg2ZmI3YjIiLCJpYXQiOjE2MDQ1ODEzMDIsImV4cCI6MTYwNDY0NjEwMn0.PH1UZq6pzGaFVscgUvpXejVaHkWCakOVxt3fme2L8aE

### check username
GET {{host}}/other_user/username/mn

### get suggestions
GET {{host}}/other_user/suggestions/?skip=0
Authorization: {{token}}

### get user by id
GET {{host}}/other_user/5f97fc1c465980150c86436a
Authorization: {{token}}

### get followers of others
GET {{host}}/other_user/followers/5f977240dc8d9205b81c580b
Authorization: {{token}}

### get following of others
GET {{host}}/other_user/following/5f977240dc8d9205b81c580b
Authorization: {{token}}

###search users
POST {{host}}/other_user/search
Content-Type: application/json
Authorization: {{token}}

{
    "query" : "kkk"
}
