@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1Zjk3NzI0MGRjOGQ5MjA1YjgxYzU4MGIiLCJpYXQiOjE2MDM3NjA3MTgsImV4cCI6MTYwMzgyNTUxOH0.o9g3w--CNZaGdGuaejoS2uaovgOOc3NShdgmZcnNjXw

### get user by id
GET {{host}}/other_user/5f969c53658cca1804acd215
Authorization: {{token}}

### get followers of others
GET {{host}}/other_user/followers/5f968a98ffc40d1a902debb2
Authorization: {{token}}

### get following of others
GET {{host}}/other_user/following/5f968a98ffc40d1a902debb2
Authorization: {{token}}