@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1Zjk3NzI0MGRjOGQ5MjA1YjgxYzU4MGIiLCJpYXQiOjE2MDM3NjA3MTgsImV4cCI6MTYwMzgyNTUxOH0.o9g3w--CNZaGdGuaejoS2uaovgOOc3NShdgmZcnNjXw

### get onlyphotos 
GET {{host}}/post/onlyphotos/5f968a98ffc40d1a902debb2/?skip=0
Authorization: {{token}}

### get my post 
GET {{host}}/post/mypost/?skip=0
Authorization: {{token}}

### get all post 
GET {{host}}/post/allpost/?skip=0
Authorization: {{token}}

### get hearted post 
GET {{host}}/post/heartedpost/?skip=0
Authorization: {{token}}

### get savedpost post 
GET {{host}}/post/savedpost/?skip=0
Authorization: {{token}}

### get sub post 
GET {{host}}/post/followingpost/?skip=0
Authorization: {{token}}

### create post
POST {{host}}/post/createpost
Content-Type: application/json
Authorization: {{token}}

{
    "title" : "title3",
    "body" : "body3",
    "picUrl" : "79aa7814c24b2f2a4349033d798017ef"
}

### like post
PUT {{host}}/post/like
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f925c3905033b162c22ff39"
}

### unlike post
PUT {{host}}/post/unlike
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f8a853c066cb3316caf1c96"
}

### heart the post
PUT {{host}}/post/hearted
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f968ab8ffc40d1a902debb7"
}

### unheart the post
PUT {{host}}/post/unhearted
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f8a853c066cb3316caf1c96"
}

### delete the particular post
DELETE  {{host}}/post/5f8ebec6c998c002a42e0783
Content-Type: application/json
Authorization: {{token}}
