@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1Zjk3ZmM3MDQ2NTk4MDE1MGM4NjQzNzMiLCJpYXQiOjE2MDQyMTM5NjUsImV4cCI6MTYwNDI3ODc2NX0.d8B5mcuEZXKkEVGqhiaz7m3R5rbMB6pvTjqUrFhaom0

### get onlyphotos 
GET {{host}}/post/onlyphotos/5f97fc70465980150c864373/?skip=0
Authorization: {{token}}

### get my post 
GET {{host}}/post/mypost/?skip=0
Authorization: {{token}}

### get all post 
GET {{host}}/post/allpost/?skip=0
Authorization: {{token}}

### get hearted post 
GET {{host}}/post/heartedpost/?skip=0
Authorization: {{token}}

### get savedpost post 
GET {{host}}/post/savedpost/?skip=0
Authorization: {{token}}

### get following post 
GET {{host}}/post/followingpost/?skip=0
Authorization: {{token}}

### get post by the user id 
GET {{host}}/post/otherspost/5f97fc2e465980150c86436c/?skip=0
Authorization: {{token}}

### create post
POST {{host}}/post/createpost
Content-Type: application/json
Authorization: {{token}}

{
    "title" : "title for the title",
    "body" : "body for the body of my post",
    "files" : [
        {
            "fileName": "95aae8815ed039ab5dbbfe4ef7131a84",
            "fileType": "image/png"
        },
        {
            "fileName": "585c460ddc2c2db407b48ded2a0fc77a",
            "fileType": "video/mp4"
        },
        {
            "fileName": "4de73f8a125cd3883c4421a4d614b25d",
            "fileType": "image/png"
        }
    ]
}
### like post
PUT {{host}}/post/like
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f925c3905033b162c22ff39"
}

### unlike post
PUT {{host}}/post/unlike
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f8a853c066cb3316caf1c96"
}

### heart the post
PUT {{host}}/post/hearted
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f968ab8ffc40d1a902debb7"
}

### unheart the post
PUT {{host}}/post/unhearted
Content-Type: application/json
Authorization: {{token}}

{
    "postId": "5f8a853c066cb3316caf1c96"
}

### delete the particular post
DELETE  {{host}}/post/5f994c57ff38710a08e98992
Content-Type: application/json
Authorization: {{token}}
