@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjhlYmRmOWM5OThjMDAyYTQyZTA3NzAiLCJpYXQiOjE2MDMxOTAyNzcsImV4cCI6MTYwMzI1NTA3N30.-dDibI9zzNrexbKLH0tCxxsI-ph81E-sMUM3_rDmwaY

### reset password
POST {{host}}/token/reset
Content-Type: application/json
Authorization: {{token}}

{
    "email" : ""
}

### new password
POST {{host}}/token/new
Content-Type: application/json
Authorization: {{token}}

{
    "password" : "akssd@aa.bb",
    "token" : "afbacd0fc2b9a0842f3a49c3fcd0b026ec5267115eb04f87b14947faa1a49a31"
}
