@host = http://localhost:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmEzZjdhOTgxMGJlNTI2OTg2ZmI3YjIiLCJpYXQiOjE2MDQ1ODEzMDIsImV4cCI6MTYwNDY0NjEwMn0.PH1UZq6pzGaFVscgUvpXejVaHkWCakOVxt3fme2L8aE

### get full 
GET {{host}}/user/full
Authorization: {{token}}

### get me 
GET {{host}}/user/me
Authorization: {{token}}

### get followers
GET {{host}}/user/followers/?skip=0
Authorization: {{token}}

### get following
GET {{host}}/user/following/?skip=0
Authorization: {{token}}

### get requests
GET {{host}}/user/requests/?skip=0
Authorization: {{token}}

### get requested
GET {{host}}/user/requested/?skip=0
Authorization: {{token}}

### register
POST {{host}}/user/register
Content-Type: application/json

{
    "fullName" : "newname",
    "userName": "oomllluo",
    "email" : "oo@gmail.com",
    "password" : "aaaaaaa"
}

### login
POST {{host}}/user/login
Content-Type: application/json

{
    "email" : "oo@gmail.com",
    "password" : "aaaaaaa"
}

### update public preference
PUT {{host}}/user/public
Content-Type: application/json
Authorization: {{token}}

### update user img
PUT {{host}}/user/img
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="img"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary--

### follow
PUT {{host}}/user/follow
Content-Type: application/json
Authorization: {{token}}

{
    "followId" : "5f97fc02465980150c864369"
}

### unfollow
PUT {{host}}/user/unfollow
Content-Type: application/json
Authorization: {{token}}

{
    "unfollowId" : "5f96ce096d968e31f4850873"
}

### request to follow
PUT {{host}}/user/requests
Content-Type: application/json
Authorization: {{token}}

{
    "reqId" : "5f968a98ffc40d1a902debb2"
}

### cancel the request
PUT {{host}}/user/cancel-req
Content-Type: application/json
Authorization: {{token}}

{
    "reqId" : "5f9239ff7ba0ba3018ad4593"
}

### accept the request
PUT {{host}}/user/accept-req
Content-Type: application/json
Authorization: {{token}}

{
    "reqId" : "5f9239ff7ba0ba3018ad4593"
}

### decline the request
PUT {{host}}/user/decline-req
Content-Type: application/json
Authorization: {{token}}

{
    "reqId" : "5f8ebec1c998c002a42e077b"
}

### save post
PUT {{host}}/user/savepost
Content-Type: application/json
Authorization: {{token}}

{
    "postId" : "5f925c3605033b162c22ff35"
}

### unsave post
PUT {{host}}/user/unsavepost
Content-Type: application/json
Authorization: {{token}}

{
    "postId" : "5f8a853b066cb3316caf1c95"
}

### update password
PUT {{host}}/user/password
Content-Type: application/json
Authorization: {{token}}

{
    "oldPass" : "aA1!aaaa",
    "newPass" : "Aa1!amja"
}

### logout
POST {{host}}/user/logout
Content-Type: application/json
Authorization: {{token}}